<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="95420" started-at="2020-09-06T15:20:23 EDT" finished-at="2020-09-06T15:21:59 EDT">
    <groups>
    </groups>
    <test name="Test" duration-ms="95420" started-at="2020-09-06T15:20:23 EDT" finished-at="2020-09-06T15:21:59 EDT">
      <class name="tests.TestCaseThree">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:tests.TestCaseThree@20322d26]" name="beforeMethod" is-config="true" duration-ms="5413" started-at="2020-09-06T15:21:28 EDT" finished-at="2020-09-06T15:21:33 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="LoginTestInvalidUser()[pri:0, instance:tests.TestCaseThree@20322d26]" name="LoginTestInvalidUser" duration-ms="15783" started-at="2020-09-06T15:21:33 EDT" finished-at="2020-09-06T15:21:49 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at tests.TestCaseThree.LoginTestInvalidUser(TestCaseThree.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestInvalidUser -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:tests.TestCaseThree@20322d26]" name="afterMethod" is-config="true" duration-ms="757" started-at="2020-09-06T15:21:49 EDT" finished-at="2020-09-06T15:21:50 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:tests.TestCaseThree@20322d26]" name="beforeMethod" is-config="true" duration-ms="5219" started-at="2020-09-06T15:21:50 EDT" finished-at="2020-09-06T15:21:55 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="LoginTestSuccess()[pri:0, instance:tests.TestCaseThree@20322d26]" name="LoginTestSuccess" duration-ms="3143" started-at="2020-09-06T15:21:55 EDT" finished-at="2020-09-06T15:21:58 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestSuccess -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:tests.TestCaseThree@20322d26]" name="afterMethod" is-config="true" duration-ms="670" started-at="2020-09-06T15:21:58 EDT" finished-at="2020-09-06T15:21:59 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- tests.TestCaseThree -->
      <class name="tests.TestCaseOne">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:tests.TestCaseOne@5025a98f]" name="beforeMethod" is-config="true" duration-ms="6481" started-at="2020-09-06T15:20:23 EDT" finished-at="2020-09-06T15:20:30 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="LoginTestInvalidUser()[pri:0, instance:tests.TestCaseOne@5025a98f]" name="LoginTestInvalidUser" duration-ms="16310" started-at="2020-09-06T15:20:30 EDT" finished-at="2020-09-06T15:20:46 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at tests.TestCaseOne.LoginTestInvalidUser(TestCaseOne.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestInvalidUser -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:tests.TestCaseOne@5025a98f]" name="afterMethod" is-config="true" duration-ms="798" started-at="2020-09-06T15:20:46 EDT" finished-at="2020-09-06T15:20:47 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:tests.TestCaseOne@5025a98f]" name="beforeMethod" is-config="true" duration-ms="5394" started-at="2020-09-06T15:20:47 EDT" finished-at="2020-09-06T15:20:52 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="LoginTestSuccess()[pri:0, instance:tests.TestCaseOne@5025a98f]" name="LoginTestSuccess" duration-ms="3212" started-at="2020-09-06T15:20:52 EDT" finished-at="2020-09-06T15:20:55 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestSuccess -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:tests.TestCaseOne@5025a98f]" name="afterMethod" is-config="true" duration-ms="1152" started-at="2020-09-06T15:20:55 EDT" finished-at="2020-09-06T15:20:57 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- tests.TestCaseOne -->
      <class name="tests.TestCaseTwo">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:tests.TestCaseTwo@49993335]" name="beforeMethod" is-config="true" duration-ms="5527" started-at="2020-09-06T15:20:57 EDT" finished-at="2020-09-06T15:21:02 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="LoginTestInvalidUser()[pri:0, instance:tests.TestCaseTwo@49993335]" name="LoginTestInvalidUser" duration-ms="16184" started-at="2020-09-06T15:21:02 EDT" finished-at="2020-09-06T15:21:18 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at tests.TestCaseTwo.LoginTestInvalidUser(TestCaseTwo.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestInvalidUser -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:tests.TestCaseTwo@49993335]" name="afterMethod" is-config="true" duration-ms="767" started-at="2020-09-06T15:21:18 EDT" finished-at="2020-09-06T15:21:19 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:tests.TestCaseTwo@49993335]" name="beforeMethod" is-config="true" duration-ms="5139" started-at="2020-09-06T15:21:19 EDT" finished-at="2020-09-06T15:21:24 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="LoginTestSuccess()[pri:0, instance:tests.TestCaseTwo@49993335]" name="LoginTestSuccess" duration-ms="2674" started-at="2020-09-06T15:21:24 EDT" finished-at="2020-09-06T15:21:27 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestSuccess -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:tests.TestCaseTwo@49993335]" name="afterMethod" is-config="true" duration-ms="751" started-at="2020-09-06T15:21:27 EDT" finished-at="2020-09-06T15:21:28 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- tests.TestCaseTwo -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
